name: Build

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            HOME_SERVER: ${{ secrets.HOME_SERVER }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: build service
              run: |
                  cd ./service
                  yarn
                  yarn build
                  cd ..

            - name: build web
              run: |
                  cd ./web
                  yarn
                  yarn build
                  cd ./dist
                  echo "{\"m.homeserver\":{\"base_url\":\"${{secrets.HOME_SERVER}}\"}}" > client.json
                  echo "{\"m.server\":\"${{secrets.HOME_SERVER}}\"}}\"}" > server.json
                  cd ../..

            - name: upload service
              uses: actions/upload-artifact@v3
              with:
                  name: service
                  path: ./service/dist

            - name: upload web
              uses: actions/upload-artifact@v3
              with:
                  name: web
                  path: ./web/dist
